-- MySQL Script generated by MySQL Workbench
-- Mon Apr 27 19:52:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sistema` DEFAULT CHARACTER SET utf8 ;
USE `db_sistema` ;

-- -----------------------------------------------------
-- Table `db_sistema`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `foto_perfil` VARCHAR(255) NULL,
  `biografia` TEXT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistema`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`tb_cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_usuario_cliente_idx` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_cliente`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_sistema`.`tb_usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistema`.`tb_profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`tb_profissional` (
  `id_profissional` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_profissional`),
  INDEX `fk_usuario_profissional_idx` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_profissional`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_sistema`.`tb_usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistema`.`tb_telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`tb_telefone` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `id_profissional` INT NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `tipo` ENUM('fixo', 'celular') NOT NULL,
  `is_whatsapp` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_telefone`),
  INDEX `fk_telefone_profissonal_idx` (`id_profissional` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_profissonal`
    FOREIGN KEY (`id_profissional`)
    REFERENCES `db_sistema`.`tb_profissional` (`id_profissional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistema`.`tb_rede_social`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`tb_rede_social` (
  `id_rede_social` INT NOT NULL AUTO_INCREMENT,
  `id_profissional` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `url_perfil` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id_rede_social`),
  INDEX `fk_rede_social_contato_idx` (`id_profissional` ASC) VISIBLE,
  CONSTRAINT `fk_rede_social_profissional`
    FOREIGN KEY (`id_profissional`)
    REFERENCES `db_sistema`.`tb_profissional` (`id_profissional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistema`.`tb_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`tb_endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `id_profissional` INT NOT NULL,
  `logradouro` VARCHAR(200) NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL,
  `cep` CHAR(9) NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_endereco_profissonal_idx` (`id_profissional` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_profissonal`
    FOREIGN KEY (`id_profissional`)
    REFERENCES `db_sistema`.`tb_profissional` (`id_profissional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistema`.`tb_projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`tb_projeto` (
  `id_projeto` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_profissional` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `data_solicitacao` DATE NOT NULL,
  `data_avaliacao` DATE NULL,
  `nota` ENUM('1', '2', '3', '4', '5') NOT NULL,
  `comentario` TEXT NULL,
  PRIMARY KEY (`id_projeto`),
  INDEX `fk_projeto_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_projeto_profissional_idx` (`id_profissional` ASC) VISIBLE,
  CONSTRAINT `fk_projeto_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `db_sistema`.`tb_cliente` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projeto_profissional`
    FOREIGN KEY (`id_profissional`)
    REFERENCES `db_sistema`.`tb_profissional` (`id_profissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistema`.`tb_portfolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`tb_portfolio` (
  `id_portfolio` INT NOT NULL AUTO_INCREMENT,
  `id_profissional` INT NOT NULL,
  `nome_portfolio` VARCHAR(100) NOT NULL,
  `data_portfolio` DATE NOT NULL,
  PRIMARY KEY (`id_portfolio`),
  INDEX `id_protfolio_profissional_idx` (`id_profissional` ASC) VISIBLE,
  CONSTRAINT `id_portfolio_profissional`
    FOREIGN KEY (`id_profissional`)
    REFERENCES `db_sistema`.`tb_profissional` (`id_profissional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistema`.`tb_nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`tb_nivel` (
  `id_nivel` INT NOT NULL AUTO_INCREMENT,
  `nome_nivel` VARCHAR(50) NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`id_nivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistema`.`tb_especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`tb_especialidade` (
  `id_especialidade` INT NOT NULL AUTO_INCREMENT,
  `nome_especialidade` VARCHAR(50) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id_especialidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistema`.`tb_competencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`tb_competencias` (
  `id_competencia` INT NOT NULL AUTO_INCREMENT,
  `id_profissional` INT NOT NULL,
  `id_especialidade` INT NOT NULL,
  `id_nivel` INT NOT NULL,
  PRIMARY KEY (`id_competencia`),
  INDEX `fk_competencia_profissional_idx` (`id_profissional` ASC) VISIBLE,
  INDEX `fk_competencia_nivel_idx` (`id_nivel` ASC) VISIBLE,
  INDEX `fk_competencia_especialidade_idx` (`id_especialidade` ASC) VISIBLE,
  CONSTRAINT `fk_competencia_profissional`
    FOREIGN KEY (`id_profissional`)
    REFERENCES `db_sistema`.`tb_profissional` (`id_profissional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_competencia_especialidade`
    FOREIGN KEY (`id_especialidade`)
    REFERENCES `db_sistema`.`tb_especialidade` (`id_especialidade`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_competencia_nivel`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `db_sistema`.`tb_nivel` (`id_nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistema`.`tb_cat_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`tb_cat_pagamento` (
  `id_cat_pagamento` INT NOT NULL AUTO_INCREMENT,
  `nome_metodo_pagamento` VARCHAR(45) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id_cat_pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistema`.`tb_midia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`tb_midia` (
  `id_midia` INT NOT NULL AUTO_INCREMENT,
  `id_portfolio` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `url_arquivo` VARCHAR(255) NOT NULL,
  `legenda` VARCHAR(140) NULL,
  PRIMARY KEY (`id_midia`),
  INDEX `fk_midia_portfolio_idx` (`id_portfolio` ASC) VISIBLE,
  CONSTRAINT `fk_midia_portfolio`
    FOREIGN KEY (`id_portfolio`)
    REFERENCES `db_sistema`.`tb_portfolio` (`id_portfolio`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sistema`.`tb_metodo_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sistema`.`tb_metodo_pagamento` (
  `id_metodo_pagamento` INT NOT NULL AUTO_INCREMENT,
  `id_profissional` INT NOT NULL,
  `id_cat_pagamento` INT NOT NULL,
  `condicao` VARCHAR(100) NULL,
  INDEX `fk_metodo_pagamento_profissional_idx` (`id_profissional` ASC) VISIBLE,
  INDEX `fk_metodo_pagamento_cat_pagamento_idx` (`id_cat_pagamento` ASC) VISIBLE,
  PRIMARY KEY (`id_metodo_pagamento`),
  CONSTRAINT `fk_metodo_pagamento_profissional`
    FOREIGN KEY (`id_profissional`)
    REFERENCES `db_sistema`.`tb_profissional` (`id_profissional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_metodo_pagamento_cat_pagamento`
    FOREIGN KEY (`id_cat_pagamento`)
    REFERENCES `db_sistema`.`tb_cat_pagamento` (`id_cat_pagamento`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
